n = int(input('Digite um numero para tabuada '))
print('-'*14)
print('{:2} X {:2} = {:2}'.format(n, 1, n*1))
print('{:2} X {:2} = {:2}'.format(n, 2, n*2))
print('{:2} X {:2} = {:2}'.format(n, 3, n*3))
print('{:2} X {:2} = {:2}'.format(n, 4, n*4))
print('{:2} X {:2} = {:2}'.format(n, 5, n*5))
print('{:2} X {:2} = {:2}'.format(n, 6, n*6))
print('{:2} X {:2} = {:2}'.format(n, 7, n*7))
print('-'*14)
